### ISSUE TITLE
cask-repair: force push if branch already exists

### ISSUE THREAD

**Issue by yurikoles** [vitorgalvao/tiny-scripts#33] opened 2016-07-28 18:20 UTC
Now there is a long multi-line comment output from git that branch can't fast-forward. 
It may be more useful to check that remote branch with same name already exists with some options to choose what to do next.

**Comment by vitorgalvao** [comment] 2016-07-29 01:35
Give me an example output.

**Comment by yurikoles** [comment] 2016-07-29 08:46
```
--------------------------------------------------------------------------------
Is everything correct? You can also make further manual edits (y/n/e) y
Submitting…
To git@github.com:yurikoles/cask-versions.git
 ! [rejected]        cask-repair_update-firefox-beta-uk -> cask-repair_update-firefox-beta-uk (fetch first)
error: failed to push some refs to 'git@github.com:yurikoles/cask-versions.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
error: the requested upstream branch 'yurikoles/cask-repair_update-firefox-beta-uk' does not exist
hint: 
hint: If you are planning on basing your work on an upstream
hint: branch that already exists at the remote, you may need to
hint: run "git fetch" to retrieve it.
hint: 
hint: If you are planning to push out a new local branch that
hint: will track its remote counterpart, you may want to use
hint: "git push -u" to set the upstream config as you push.
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"
Error creating pull request: Unprocessable Entity (HTTP 422)
Invalid value for "head"

There was an error submitting the pull request. Have you forked the repo and made sure the pull and push remotes exist?```

**Comment by vitorgalvao** [comment] 2016-07-29 19:47
Looks like the branch already existed. Delete it first. Closing, as I cannot reproduce. Need a reproduceable test case.

**Comment by yurikoles** [comment] 2016-08-15 00:12
Yes, I do have it. It's obvious for those who contribute a lot. I mean that this is not so rare situation, I though it needs more user-friendly message and offer to drop old remote branch.

**Comment by vitorgalvao** [comment] 2016-08-15 09:57
Agreed.

**Comment by vitorgalvao** [comment] 2016-09-02 15:37
Done.

**Closed by vitorgalvao** 2016-09-02 15:37 UTC
